---

plugin: netbox.netbox.nb_inventory
api_endpoint: http://localhost:8001
interfaces: true
ip_addresses: true
config_context: true
custom_fields: true

ansible_host_dns_name: True


headers:
  Authorization: "Bearer nbt_HmR5bROfRCS0.S9jtuyLOAnr9PV8LA7evYSc0bnH2oH7klOdZBwup"

token: "HmR5bROfRCS0.S9jtuyLOAnr9PV8LA7evYSc0bnH2oH7klOdZBwup"
validate_certs: true

group_by: 
  - sites
