all:
  hosts:
    leaf1:
    leaf2:
    leaf3:
    leaf4:
    spine1:
    spine2:
    spine3:
    spine4:
    mgmt1:
    WAN1:
    WAN2:
  vars:
    backup_dir: "/etc/ansible/configs"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    ansible_network_os: nvidia.nvue.httpapi
    ansible_httpapi_port: 8765
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_httpapi_password: 'Lab123'
    ansible_user: 'cumulus'
    ansible_password: 'Lab123'
    target_user: 'cumulus'
    ssh_pubkey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCvjs/RFPhxLQMkckONg+1RE1PTIO2JQhzFN9TRg7ox7o0tfZ+IzSB99lr2dmmVe8FRWgxVjc/V1RlmUck6M2ZL8G/jpHOvxtDTrcPo0q3de1ttmxpNpTz1nezOIegyY4yobDejYoPeXRX1mTwNPc9c/Gb00hOaoZo0Ae2laeSH8iofNpV6QHMTwxWdTXI0TZdZhVqgvDQMwL2wqXC03hxAtECs5znmWzf4gdeSmFVSCiS+OiLIwlqChwhFmbkxWCW2LSrPJkQ+QbdMJSx9JjWRL+IH9L2ikxsP6aE2h5K1hgMVTjiJMeYgHH9gPXa+Hywfu8W2TptFnAA2K4VSa6JPRHfjR3iieA2ZlDJD6M/4X4V+mhiVBf7CxKinpfcpZvMj4qVPgdfwINhV6iHp1V76WY5BJ4/V357i6sWBPw8k9+Ju4JNTPqGneKMovcF5z3u22ll4cndgIK+F/hbmNGH73GrcsMroYnYCmZst3i9aV4Ro5WBlsflmTgA96uLuqxk="
    ssh_authorized_key_path: "/home/cumulus/.ssh/authorized_keys"
    disable_password_auth: false   # set to false if you don't want to harden SSH
    post_login_message: |
                #####################################################################################
                #                     You are successfully logged in to: {{ hostname }}                   #
                #####################################################################################
leafs:
  hosts:
    leaf1:
    leaf2:
    leaf3:
    leaf4:
  vars:
    vxlan_interfaces:
      - id: swp16
        vlan: 100
    vlans:
      - id: '100'
        vnis:
          - '100'
      - id: '200'
        vnis:
          - '200'


spines:
  hosts:
    spine1:
    spine2:
    spine3:
    spine4:

WANs:
  hosts:
    WAN1:
    WAN2:
  vars:
    wan_interfaces:
    - swp1
    - swp16

